id: IAA21926D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T17:17:46+00:00'
last_modified: '2022-06-09T04:28:12.801301+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2CZ5988
  title: ངག་དབང་འཇམ་དབྱངས་རྒྱལ་མཚན་གྱི་རྣམ་ཐར་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    CA09:
      image_group_id: I1KG969
      title: Volume 1 of ngag dbang 'jam dbyangs rgyal mtshan gyi rnam thar
      total_pages: 520
      order: 1
      base_file: CA09.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
