id: P007064
initial_creation_type: ocr
source_metadata:
  id: bdr:W2CZ5988
  title: ངག་དབང་འཇམ་དབྱངས་རྒྱལ་མཚན་གྱི་རྣམ་ཐར་
  author: ''
  volumes:
    a01c61dd9c434685a5a676fd91263d17:
      image_group_id: I1KG969
      title: ''
      volume_number: 1
      total_pages: 520
ebook_metadata:
  title: ངག་དབང་འཇམ་དབྱངས་རྒྱལ་མཚན་གྱི་རྣམ་ཐར་
  author: ''
  sku: P007064
  cover: cover.jpg
  layers:
  - pagination
