id: P007064
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 2021-12-17 12:39:16.632736
source_metadata:
  id: bdr:W2CZ5988
  title: ངག་དབང་འཇམ་དབྱངས་རྒྱལ་མཚན་གྱི་རྣམ་ཐར་
  author: ''
  volumes:
    faaf5e2fe0f84b538d5da13e6422da5b:
      image_group_id: I1KG969
      title: Volume 1 of ngag dbang 'jam dbyangs rgyal mtshan gyi rnam thar
      volume_number: 1
      total_pages: 520
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
